apiVersion: v1
kind: Secret
metadata:
  name: {{ include "production-service.fullname" . }}-secret
  labels:
    {{- include "production-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  PRODUCTION_AMQP_URL: {{ .Values.config.productionAmqpUrl | quote }}
  {{- if .Values.secret.mongoUri }}
  PRODUCTION_MONGO_URI: {{ .Values.secret.mongoUri | quote }}
  {{- end }}
